version: "3.8"

services:
  angular-app:
    build: .
    container_name: angular-prod
    ports:
      - "4200:80"
    networks:
      - angular-network

networks:
  angular-network:
    driver: bridge
